### PR TITLE
Scientific calculator added

### PR DESCRIPTION
**Pull request by akshit5565**

### CODE REVIEW

**Comment by letdummy** [comment]
Hi, you want update its folder number by yourself or you want me to do it, it both works for me

**Comment by letdummy** [comment]
Anw, Thank you for your participation, will merge this ASAP

**Comment by akshit5565** [comment]
Better you do it !!

**Comment by letdummy** [comment]
LOL, ok

**Comment by letdummy** [comment]
Hi, I will merge this now, If you want to add a new project, you can submit a new PR, Thank you 👏

**Pull request merged**
