### PR TITLE
nft Preview Card Component

### PR DESCRIPTION
**Pull request by SayanTan772**
I have added my project in a separate folder named "nft Preview Card Component" and included a README.md file describing my project. I have also added some additional resources in the README file that ought to help out anyone who seeks to learn from this project !

### CODE REVIEW

**Comment by letdummy** [comment]
LGTM, will merge this later after I finished reviewing all PR available, thanks for your participation. 👏 don't forget to star this repo ❤️

**Comment by SayanTan772** [comment]
@letdummy I am sorry but I have to close this PR before you merge it ( due to plagiarism issues I was previously unaware of ! ). I am still new to Hacktober fest so I am still figuring out the dos and don'ts. May I send another PR request for a different project ??

**Comment by letdummy** [comment]
Sure, will love to see your next project,

**Comment by SayanTan772** [comment]
@letdummy can you please remove the accepted tags from this and mark this as invalid. I mean If it's possible right now 😃. Thank you  !

**Pull request closed without merging**
