### PR TITLE
added image compressor project

### PR DESCRIPTION
**Pull request by Sanket-Gawande**

### CODE REVIEW

**Comment by Sanket-Gawande** [comment]
added new project image compressor , install dependencies using command yarn or npm i to and run the project

**Comment by letdummy** [comment]
Hi, can you rename your folder number to 42? coz if you don't I will do it anyway (later after I merge some PR)

**Comment by Sanket-Gawande** [comment]
ok ill add count & commit it again.

**Comment by letdummy** [comment]
I will do it for you, my friend 👏 hope you OK with that

**Pull request merged**
