### PR TITLE
Added book finder website and fixed images + .gitignore for #2

### PR DESCRIPTION
**Pull request by jbecker7**
I added a cool book finder website from another open-source project and modified it a bit. I grouped this with my original PR, which was just to fix the template for #2 a bit

### CODE REVIEW

**Comment by letdummy** [comment]
So, you change your niche into book finder, LGTM, thank you for participating, 🌟

**Comment by jbecker7** [comment]
@letdummy Thank you! Can you please accept it?

**Comment by letdummy** [comment]
I already tagged this as accepted, it should be update your progress at Hacktoberfest2022, but if it doesn't please lmk with a screenshot in this comment section, thank you 👏

**Comment by jbecker7** [comment]
Screen Shot 2022-10-03 at 8 34 40 AM
@letdummy

**Comment by letdummy** [comment]
hey, wsup buddy? did your progress at Hacktoberfest2022 says that this PR/MRs [NOT ACCEPTED] ??

**Comment by jbecker7** [comment]
Screen Shot 2022-10-05 at 9 21 21 AM
@letdummy

**Pull request closed without merging**
