### PR TITLE
Dice up! game

### PR DESCRIPTION
**Pull request by sanjana317**
Added a dice game called Dice up!
issue: #142

### CODE REVIEW

**Comment by letdummy** [comment]
can you rename your folder into 64. your_project_name(don't forget the space)
like what #136  and #138 did, I want this commit shows your name when ppl open it in the main branch 😇

**Comment by sanjana317** [comment]
Yes I've made the necessary changes

**Comment by letdummy** [comment]
you forgot the space 😭 but It's okay, coz it's only minor error, anw Thanks for participating

**Comment by sanjana317** [comment]
Oh I'm sorry I'll keep that in mind next time

**Pull request merged**
