### PR TITLE
Ci: Added new project

### PR DESCRIPTION
**Pull request by Ashish-khanagwal**
Added new web dev project made with HTML and advanced CSS

### CODE REVIEW

**Comment by letdummy** [comment]
your PR has same error with #26 please fix this folder problem, follow this step regarding this problem on github https://stackoverflow.com/questions/12258399/how-do-i-create-a-folder-in-a-github-repository

**Comment by Ashish-khanagwal** [comment]
hey,  can you please review it now?
If further changes are required, Let me know .
Thank you

**Comment by letdummy** [comment]
Nice, you fixed it, thank you for your participation 👏 , don't forget to leave a star 🌟

**Comment by Ashish-khanagwal** [comment]
Thank you for support and for the opportunity, Surely will add a star⭐

> Nice, you fixed it, thank you for your participation 👏 , don't forget to leave a star 🌟
>

**Pull request merged**
